# -*- coding: utf-8 -*-
"""
/***************************************************************************
 extenstmatcher
                                 A QGIS plugin
 match raster's extent
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-03
        copyright            : (C) 2026 by Roshin Syahdan
        email                : rnrfsn@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load extenstmatcher class from file extenstmatcher.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .extent_matcher import extenstmatcher
    return extenstmatcher(iface)
