# -*- coding: utf-8 -*-
"""
/***************************************************************************
 extenstmatcherDialog
                                 A QGIS plugin
 match raster's extent
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-03
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Roshin Syahdan
        email                : rnrfsn@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.gui import QgsMapLayerComboBox, QgsFileWidget
from qgis.core import QgsMapLayerProxyModel

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'extent_matcher_dialog_base.ui'))


class extenstmatcherDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(extenstmatcherDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        from qgis.core import QgsMapLayerProxyModel

        self.lcbOriginalRaster.setFilters(QgsMapLayerProxyModel.RasterLayer)
        
        self.lcbTargetRaster.setFilters(QgsMapLayerProxyModel.RasterLayer)

        self.Output.setStorageMode(QgsFileWidget.SaveFile)

        self.Output.setFilter("GeoTIFF (*.tif *.tiff);;ASCII Grid (*.asc)")



        
